server:
  port: 8081

eureka:
  client:
    fetch-registry: true 
    registry-with-eureka: true 
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri:
              http://localhost:8080/realms/DigitalMedia
        registration:
          keycloak:
            client-id: api-gateway
            client-secret: drlrV2c6uBJAJWcaNtkeNkSzU7xrlCd3
            scope: openid
            redirect-uri: http://localhost:8081/

  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: movieRoute
          uri: lb://movie-service
          predicates:
            - Path=/movies/**
          filters:
            - RemoveRequestHeader=Cookie

        - id: catalogRoute
          uri: lb://catalog-service
          predicates:
            - Path=/catalog/**
          filters:
            - RemoveRequestHeader=Cookie
        - id: serieRoute
          uri: lb://serie-service
          predicates:
            - Path=/series/**
          filters:
            - RemoveRequestHeader=Cookie
